services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgrest_public_safety_incidents
    ports:
      - "5432:5432"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
  postgrest-public-safety-incidents:
    image: postgrest/postgrest:v13.0.0
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/postgrest_public_safety_incidents
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgrest_web_anon #In production this role should not be the same as the one used for the connection
      PGRST_JWT_SECRET: $PGRST_JWT_SECRET_PUBLIC_SAFETY_INCIDENTS
      PGREST_MAX_ROWS: 10000
    ports:
      - "3000:3000"